x = input('me fala alguma coisa ')
print('o tipo primitivo disso é', type(x))
print('ele está em minúsculo?', x.isupper())
print('ele está em maiúsculo?', x.islower())
print('está capitalizada?', x.istitle())
print('só tem espaços?', x.isspace())
print('ele é um dígito?', x.isdigit())
print('ele é printable?', x.isprintable())
print('ele é identifier?', x.isidentifier())
print('ele é um número?', x.isnumeric())
print('ele é alfabético?', x.isalpha())
print('ele é alphanumérico?', x.isalnum())
