print('\033[34m▀▄▀▄▀▄▀▄▀▄▀▄\033[m'*6)
print('\033[30mSeja muito bem vindo(a) ao melhor serviço de aluguel de carros do Brasil!\033[m')
print('\033[34m▀▄▀▄▀▄▀▄▀▄▀▄\033[m'*6)
dias = int(input('\033[30mPor quantos dias o carro ficou alugado? '))
km = float(input('Quantos quilômetros foram percorridos com o carro? '))
valor = (dias * 60)+(km * 0.15)
print(f'O carro foi alugado por {dias} dias e foram percorridos {km} quilômetros. O valor a ser pago é R$:{valor:.2f}')
print('Muito obrigado pela preferência, volte sempre!')
