nome = str(input('Digite seu nome completo: ')).strip()
separado = nome.split()
print(nome.upper())
print(nome.lower())
print(f'O seu nome possui {len("".join(separado))} letras')
print(f'O seu primeiro nome possui {len(separado[0])} letras')
#Ao invés de separar com o split eu poderia ter feito o terceiro print assim: print(f'O seu nome possui {len(nome) - nome.count(" ")} letras')
#no quarto print eu poderia ter feito assim: print(f'O seu primeiro nome possui {nome.find(" ")} letras')
